// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Location.Entities.Models;
using Microsoft.EntityFrameworkCore;

namespace Location.Repository.Database.Context;

public partial class LocationContext : DbContext
{
    public LocationContext()
    {
    }

    public LocationContext(DbContextOptions<LocationContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Categorie> Categories { get; set; }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Location.Entities.Models.Location> Locations { get; set; }

    public virtual DbSet<Marque> Marques { get; set; }

    public virtual DbSet<Vehicule> Vehicules { get; set; }


#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=LOCATION_VEHICULE;Integrated Security=True");
        optionsBuilder.LogTo(Console.WriteLine);
    }
        

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Categorie>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CATEGORI__3214EC27236345A0");
        });

        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CLIENT__3214EC2722123CF8");
        });

        modelBuilder.Entity<Location.Entities.Models.Location>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LOCATION__3214EC2737DB25A1");

            entity.HasOne(d => d.IdClientNavigation).WithMany(p => p.Locations).HasConstraintName("FK__LOCATION__ID_CLI__30F848ED");

            entity.HasOne(d => d.IdVehiculeNavigation).WithMany(p => p.Locations).HasConstraintName("FK__LOCATION__ID_VEH__31EC6D26");
        });

        modelBuilder.Entity<Marque>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MARQUE__3214EC270B94C813");
        });

        modelBuilder.Entity<Vehicule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__VEHICULE__3214EC271F428590");

            entity.HasOne(d => d.IdCategorieNavigation).WithMany(p => p.Vehicules).HasConstraintName("FK__VEHICULE__ID_CAT__2E1BDC42");

            entity.HasOne(d => d.IdMarqueNavigation).WithMany(p => p.Vehicules).HasConstraintName("FK__VEHICULE__ID_MAR__2D27B809");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}