//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Location.ViewConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Location.ViewConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un client.
        /// </summary>
        internal static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une location.
        /// </summary>
        internal static string AddLocation {
            get {
                return ResourceManager.GetString("AddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le client avec l&apos;id.
        /// </summary>
        internal static string ClientNonExistent {
            get {
                return ResourceManager.GetString("ClientNonExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment supprimer ce client ainsi que ces locations de façon permanente ?.
        /// </summary>
        internal static string ConfirmDeleteClient {
            get {
                return ResourceManager.GetString("ConfirmDeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment supprimer cette location de façon permanente ?.
        /// </summary>
        internal static string ConfirmDeleteLocation {
            get {
                return ResourceManager.GetString("ConfirmDeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer un client.
        /// </summary>
        internal static string DeleteClient {
            get {
                return ResourceManager.GetString("DeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer une location.
        /// </summary>
        internal static string DeleteLocation {
            get {
                return ResourceManager.GetString("DeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher tous les clients.
        /// </summary>
        internal static string DisplayAllClients {
            get {
                return ResourceManager.GetString("DisplayAllClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher toutes les locations.
        /// </summary>
        internal static string DisplayAllLocations {
            get {
                return ResourceManager.GetString("DisplayAllLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher un client par son Id.
        /// </summary>
        internal static string DisplayClientById {
            get {
                return ResourceManager.GetString("DisplayClientById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher une location par son Id.
        /// </summary>
        internal static string DisplayLocationById {
            get {
                return ResourceManager.GetString("DisplayLocationById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez son adresse.
        /// </summary>
        internal static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez son date de naissance.
        /// </summary>
        internal static string EnterBirthDate {
            get {
                return ResourceManager.GetString("EnterBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez sa ville.
        /// </summary>
        internal static string EnterCity {
            get {
                return ResourceManager.GetString("EnterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez l&apos;id du client.
        /// </summary>
        internal static string EnterClientId {
            get {
                return ResourceManager.GetString("EnterClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez son nombre de km.
        /// </summary>
        internal static string EnterDistance {
            get {
                return ResourceManager.GetString("EnterDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez sa date de fin.
        /// </summary>
        internal static string EnterEndDate {
            get {
                return ResourceManager.GetString("EnterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez son prénom.
        /// </summary>
        internal static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez son nom.
        /// </summary>
        internal static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez l&apos;id de la location.
        /// </summary>
        internal static string EnterLocationId {
            get {
                return ResourceManager.GetString("EnterLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez son code postal.
        /// </summary>
        internal static string EnterPostalCode {
            get {
                return ResourceManager.GetString("EnterPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez sa date de départ.
        /// </summary>
        internal static string EnterStartDate {
            get {
                return ResourceManager.GetString("EnterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez l&apos;id du véhicule.
        /// </summary>
        internal static string EnterVehicleId {
            get {
                return ResourceManager.GetString("EnterVehicleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choix non valide !.
        /// </summary>
        internal static string InvalidChoice {
            get {
                return ResourceManager.GetString("InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le client avec l&apos;id {id} n&apos;existe pas.
        /// </summary>
        internal static string InvalidClientIdExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidClientIdExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des locations des clients.
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous afficher ses locations ?.
        /// </summary>
        internal static string MenuClient {
            get {
                return ResourceManager.GetString("MenuClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   0 : Quitter.
        /// </summary>
        internal static string QuitChoice {
            get {
                return ResourceManager.GetString("QuitChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci d&apos;avoir utilisé le service de gestion de location, à bientot!.
        /// </summary>
        internal static string QuitMessage {
            get {
                return ResourceManager.GetString("QuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour un client.
        /// </summary>
        internal static string UpdateClient {
            get {
                return ResourceManager.GetString("UpdateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour une location.
        /// </summary>
        internal static string UpdateLocation {
            get {
                return ResourceManager.GetString("UpdateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyer sur une touche pour continuer....
        /// </summary>
        internal static string WaitKeyMessage {
            get {
                return ResourceManager.GetString("WaitKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
